spring.application.name=L5
spring.config.import=file:env.properties
server.port=${PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PW}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
#CLOUDINARY
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.username=${CLOUDINARY_USERNAME}
cloudinary.secret=${CLOUDINARY_SECRET}
#JWT
jwt.secret=${JWT_SECRET}
